#!/bin/bash

# see https://stackoverflow.com/questions/4468157/how-can-i-create-a-waveform-image-of-an-mp3-in-linux

read -d '' filter <<EOM
[0:a]avectorscope=s=640x518,pad=1280:720[vs];
[0:a]showspectrum=mode=separate:color=intensity:scale=cbrt:s=640x518[ss];
[0:a]showwaves=s=1280x202:mode=line[sw];
[vs][ss]overlay=w[bg];
[bg][sw]overlay=0:H-h,drawtext=fontfile=/usr/share/fonts/TTF/Vera.ttf:fontcolor=white:x=10:y=10:text='"Song Title" by Artist'[out]
EOM

ffmpeg -i "$1"                \
    -filter_complex "$filter" \
    -map "[out]"              \
    -map 0:a                  \
    -c:v libx264              \
    -preset fast              \
    -crf 18                   \
    -c:a copy                 \
    output.mkv
