#!/bin/bash
shopt -s extglob


########
# rdy? #
########

_set_pa_source() {
    case $source_type in
        mic)
            # TODO get pa sources and match index

            if _shift_argv
            then
                source="alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback"

            else
                # index: 0 (plug headset in) also works
                source="alsa_input.hw_0_0"
            fi
            ;;

        mon?(itor))
            source="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback.monitor"
            ;;

        *)
            return -1
            ;;
    esac
}


_set_out() {
    out=$(printf "$pout" "${FUNCNAME[1]}.$source_type")
    _log "\$out is $out"
}


#
# progs #
#

convert() {
    cmd=("sox \$in_file \$out_file")
}


# location
from() {
    _shift_argv_into_var "in_file"
}


# location
into() {
    to
}


# location
to() {
    _shift_argv_into_var "out_file"
}


# type
pa() {
    service="pulseaudio.service"
}


# action
parse() {
    cmd=("awk -f \$awk_script \$in_file")
    if _has_prog "^(into|to)$"
    then cmd+=("> \$out_file")
    fi
}


# type
meta() {
    awk_script="$BEAT/dat-meta.awk"
}

#
# rec [from] [mic|mon(itor)]
#
# action
rec() {
    cmd=("parec -d \$source --file-format=wav \$out.wav")
    [[ ${argv[0]} != "from" ]] || _shift_argv   # ignore "from"; just reads better...
    _shift_argv_into_var "source_type"
    if _set_pa_source
    then _set_out
    else _exit "no source type matching \"$source_type\""
    fi
}


# action
reset() {
    cmd=("systemctl --user restart \$service")
}


# should be a verb with ``pa``, like ``get pa sources``
sources() {
    cmd=("pacmd list-sources | grep -A1 index: | awk -f $BEAT/parse-pa.awk")
}


########
# set. #
########

source .blang
argc=$#
argv=("$@")
cmd=()

BEAT=$(dirname $0)

in_file=
out_file=                               # TODO diff between this and below?
out=                                    # output filename
pout="/tmp/beat.%s.$(date +"%s")"       # partial name of output file


########
# go!! #
########

_process_argv
_run_cmd
