#!/bin/bash


########
# rdy? #
########

_rec() {
    out=$(printf "$pout" ${FUNCNAME[1]})
    cmd=("parec -d" $src "--file-format=wav $out.wav")
    _run_cmd
}


# verbs #

mic() {
    # index: 0 (untested successfully)
    src="alsa_input.hw_0_0"

    # index: 3 (tested; plug headset in)
    # src="alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback"
    _rec
}


mon() {
    src="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback.monitor"
    _rec
}


filter() {
    # remove silence from beginning and end
    read -d '' audio_filters <<EOM
silenceremove=1:0:-50dB,
areverse,
silenceremove=1:0:-50dB,
areverse
EOM

    ffmpeg -i "$out.wav" \
        -af "$audio_filters" \
        "$out.filtered.wav"
}


########
# set. #
########

source .blang
argc=$#
argv=("$@")
cmd=()

out=                                        # output filename
pout="/tmp/beat-brec.%s.$(date +"%s")"      # partial name of output file
sink=
src=


########
# go!! #
########

_process_argv
_run_cmd
