#!/bin/awk -f

@include "init.awk"
BEGIN {
  RS = "\r\n"
  timed = 1
  for (i=1; i<=end; i++)
    print_frame(act_on_frame(i))
}

function act_on_frame(i) {
  switch (action) {
    case "sine_wave":
      if (!repeat) repeat = 1
      wav = sine_wave(i)
      return wav " " wav
      break

    default:
      return i
  }
}

function sine_wave(i) {
   return sprintf("%20s", sin(i/end*repeat*2*pi))
}
