#!/bin/bash


# output file
out=/tmp/sine-$1

# create dat file with awk
awk -v frequency=$1                     \
    -f "$(dirname "$0")"/create-wav.awk \
    >$out.dat

# convert dat to wav file
sox $out.dat $out.wav

# play the created wav file
play $out.wav
