#!/bin/bash
#
# $ ./recmic output_file
#
# records from internal mic source into `output_file'


########
# rdy? #
########


########
# set. #
########

source="alsa_input.hw_0_0" # index: 0
source="alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback" # index: 3
out=${1-/tmp/beat-recmic.$(date +"%s")}


########
# go!! #
########

parec -d "$source" --file-format=wav "$out".wav
wait
