#!/bin/bash
#
# $ ./recmon output_file
#
# records from internal speakers' monitor source into `output_file'


########
# rdy? #
########

set_monitor() {
    # from the cli, run `pacmd list', note the `monitor source' for the
    # speakers' sink, use that source's name
    # monitor="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink.monitor"
    monitor="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback.monitor"
}


########
# set. #
########

monitor=
out=${1-/tmp/beat-recmon.$(date +"%s")}


########
# go!! #
########

set_monitor
parec -d "$monitor" --file-format=wav "$out".wav
wait

# remove silence, etc. with ffmpeg audio filters
{
    read -d '' audio_filters <<EOM
silenceremove=1:0:-50dB,
areverse,
silenceremove=1:0:-50dB,
areverse
EOM

    ffmpeg -i "$out".wav \
        -af "$audio_filters" \
        "$out".silenceremove.wav
}
