#!/bin/bash

cam="/dev/video0"

# internal mic
mic="alsa_input.hw_0_0"

# headset mic
# mic="alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback"

ffmpeg -y \
    -f pulse -i $mic \
    -f v4l2 -i $cam \
    -f tee \
        -map 0:a -c:a copy \
        -map 1 -c:v copy "output.mkv|[f=nut]pipe:" \
    | ffplay pipe:
